@startuml

class Comercio {
	
	- Productos[] productos;
	- Historial [] operaciones;
	
	+ public crearInsumo();
	+ public crearServicioDeArmado();
	+ public crearServicioDeReparacion();
	+ public buscarProductoPorNombre();
	+ public modificarPrecioListaProducto ();	
	+ public addOperacion();
	+ public mostrarHistorialDeOperaciones();
	+ public mostrarProductoDisponibleParaVenta();
	
 
}


abstract class Productos implements Matematica{

	- String nombre;
	- double precioLista;
	
	{abstract} clonar()

}


class ProductoYaIngresadoException{
	- Productos producto;
	
	+ productoYaIngresado();
}


class ProductoNoEncontradoException{
	- Productos producto;
		
	+ productoNoEncontrado();
}


class Operaciones{
 	
 	- String nombre;
 	- String fechaVenta;
 	- double precioLista;
 	
}


class Insumos{

	- String tipo;
	- Double procentajeGanancia;
	
	+ devolverMontoFacturacion();

}

class Servicios{
	
	- Double horasOcupaServicio;
	
	+ devolverMontoFacturacion();


}

class ServicioArmado{



}

class ServicioReparacion{
	
	- Dificultad dificultad;
	
}

enum Dificultad{
	private int dificultad;
}

ServicioReparacion ..down Dificultad

interface Matematica{
	
	+ Double resultado;
	+ Double delta;

	public default sumarPorcentaje();
}


Comercio "1" -- "1..*" Operaciones
Comercio "1" -- "1..*" Productos
Productos "1" -- "1..*" ProductoYaIngresadoException
Productos "1" -- "1..*" ProductoNoEncontradoException


Productos <|-- Insumos
Productos <|-- Servicios
Servicios <|-- ServicioArmado
Servicios <|-- ServicioReparacion

@enduml